#include "area_target_runtime.h"
#include <algorithm>
#include <array>
#include <cmath>
#include <cstring>
#include <filesystem>
#include <fstream>
#include <functional>
#include <iostream>
#include <limits>
#include <sstream>
#include <stdexcept>
#include <string>
#include <vector>
#define CHECK(c) do{if(!(c))throw std::runtime_error(#c);}while(0)
using Matrix=std::array<float,16>;
static constexpr double pi=3.14159265358979323846;
static int cases=0,failures=0;
static void test(const std::string& name,const std::function<void()>& body){try{body();++cases;}catch(const std::exception& e){++failures;std::cerr<<name<<": "<<e.what()<<'\n';}}
static std::string readFixture(const char* name){const auto path=std::filesystem::path(__FILE__).parent_path().parent_path().parent_path()/"tests/fixtures/cross_platform"/name;std::ifstream f(path);CHECK(f.good());return std::string(std::istreambuf_iterator<char>(f),{});}
static double number(const std::string& json,const char* key){const auto start=json.find(std::string("\"")+key+"\"");CHECK(start!=std::string::npos);const auto colon=json.find(':',start);CHECK(colon!=std::string::npos);return std::stod(json.substr(colon+1));}
static Matrix array(const std::string& json,const char* key){const auto start=json.find(std::string("\"")+key+"\"");CHECK(start!=std::string::npos);const auto left=json.find('[',start),right=json.find(']',left);CHECK(left!=std::string::npos&&right!=std::string::npos);std::string content=json.substr(left+1,right-left-1);std::replace(content.begin(),content.end(),',',' ');std::istringstream f(content);Matrix m{};for(auto& value:m)CHECK(bool(f>>value));return m;}
static Matrix identity(){return {1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1};}
static Matrix multiply(const Matrix& a,const Matrix& b){Matrix m{};for(int i=0;i<4;++i)for(int j=0;j<4;++j)for(int k=0;k<4;++k)m[i*4+j]+=a[i*4+k]*b[k*4+j];return m;}
static Matrix inverse(const Matrix& a){Matrix m=identity();for(int i=0;i<3;++i){for(int j=0;j<3;++j)m[i*4+j]=a[j*4+i];for(int j=0;j<3;++j)m[i*4+3]-=m[i*4+j]*a[j*4+3];}return m;}
static Matrix rotateZ(double radians,float x=0,float y=0,float z=0){auto m=identity();m[0]=m[5]=std::cos(radians);m[1]=-std::sin(radians);m[4]=std::sin(radians);m[3]=x;m[7]=y;m[11]=z;return m;}
static void copy(const Matrix& m,float* out){std::copy(m.begin(),m.end(),out);}
static Matrix matrix(const float* values){Matrix m{};std::copy_n(values,16,m.begin());return m;}
static void near(const float* actual,const Matrix& expected,float tolerance=.0001f){for(size_t i=0;i<expected.size();++i)CHECK(std::fabs(actual[i]-expected[i])<=tolerance);}
static ATCSessionConfigV2 config(){const auto json=readFixture("session-sequence-v2.json");ATCSessionConfigV2 c{};c.struct_size=sizeof(c);c.api_version=2;c.window_size=number(json,"window_size");c.initialization_samples=number(json,"initialization_samples");c.recovery_samples=number(json,"recovery_samples");c.max_translation_residual_m=number(json,"max_translation_residual_m");c.max_rotation_residual_rad=number(json,"max_rotation_residual_rad");c.max_pose_skew_ns=number(json,"max_pose_skew_ns");c.max_alignment_age_ns=number(json,"max_alignment_age_ns");c.max_result_age_ns=number(json,"max_result_age_ns");c.smoothing_tau_seconds=number(json,"smoothing_tau_seconds");return c;}
static ATCResultV2 raw(uint64_t frame,uint64_t time,const Matrix& pose,bool matched=true){ATCResultV2 r{};r.struct_size=sizeof(r);r.api_version=2;r.status=matched?ATC_OK:ATC_NO_MATCH;r.raw_pose_valid=matched;r.frame_id=frame;r.capture_timestamp_ns=time;r.map_generation=7;r.capture_clock_epoch=11;r.camera_id=2;r.map_instance_id=31;r.inliers=matched?100:0;r.confidence=matched?.9f:0;copy(pose,r.camera_from_scan);return r;}
static ATCTrackingSampleV2 tracking(const ATCResultV2& r,const Matrix& pose){ATCTrackingSampleV2 t{};t.struct_size=sizeof(t);t.api_version=2;t.frame_id=r.frame_id;t.capture_timestamp_ns=r.capture_timestamp_ns;t.map_generation=r.map_generation;t.capture_clock_epoch=r.capture_clock_epoch;t.camera_id=r.camera_id;t.pose_timestamp_ns=r.capture_timestamp_ns;t.tracking_epoch=4;t.clock_mapping_valid=t.pose_valid=t.extrinsics_valid=1;t.tracking_quality=ATC_TRACKING_QUALITY_NORMAL;copy(pose,t.world_from_camera);return t;}
struct Session{
 ATCSessionHandle h=nullptr;
 explicit Session(const ATCSessionConfigV2& c=config()){CHECK(atc_session_create(&c,&h)==ATC_OK&&h);}
 ~Session(){atc_session_destroy(&h);}
 ATCSessionResultV2 update(const ATCResultV2& r,const ATCTrackingSampleV2* t=nullptr,ATCStatus expected=ATC_OK){ATCSessionResultV2 out{};out.struct_size=sizeof(out);out.api_version=2;CHECK(atc_session_update(h,&r,t,&out)==expected);CHECK(out.status==expected);return out;}
};
static void ready(Session& s,const Matrix& cameraFromScan,const Matrix& worldFromCamera,uint64_t begin=1,uint64_t timestamp=100000000){for(uint64_t i=0;i<3;++i){auto r=raw(begin+i,timestamp+i*10000000,cameraFromScan);auto t=tracking(r,worldFromCamera);const auto out=s.update(r,&t);CHECK(out.raw_pose_valid);CHECK(out.alignment_valid==(i==2));}}
int main(){try{
 const auto coordinate=readFixture("coordinate-contract-v2.json");const Matrix cs=array(coordinate,"cameraFromScan"),wc=array(coordinate,"worldFromCamera"),ws=array(coordinate,"expectedWorldFromScan");
 test("Raw without tracking preserves nonidentity pose",[&]{Session s;const auto r=raw(0,0,cs);auto out=s.update(r);CHECK(out.raw_pose_valid&&!out.alignment_valid&&!out.propagated_pose_valid&&out.mode==ATC_MODE_RAW&&out.rejection_reason==ATC_REJECTION_NO_TRACKING);near(out.camera_from_scan,cs);CHECK(out.map_generation==7&&out.map_instance_id==31&&out.capture_clock_epoch==11&&out.camera_id==2);});
 test("bad first bootstrap seed cannot poison later consistent samples",[]{
  Session s;auto r=raw(0,0,identity());auto t=tracking(r,rotateZ(0,10));CHECK(!s.update(r,&t).alignment_valid);
  ATCSessionResultV2 out{};
  for(uint64_t i=1;i<=3;++i){r=raw(i,i*2000000000,identity());t=tracking(r,identity());out=s.update(r,&t);CHECK(out.raw_pose_valid);}
  CHECK(out.alignment_valid&&out.state==ATC_SESSION_TRACKING);near(out.world_from_scan,identity());
 });
 test("bad first recovery seed cannot poison later consistent samples",[&]{
  Session s;ready(s,cs,wc);auto r=raw(4,2000000000,identity(),false);auto t=tracking(r,wc);CHECK(s.update(r,&t,ATC_NO_MATCH).state==ATC_SESSION_LOST);
  r=raw(5,4000000000,identity());t=tracking(r,rotateZ(0,10));CHECK(!s.update(r,&t).alignment_valid);
  ATCSessionResultV2 out{};for(uint64_t i=0;i<2;++i){r=raw(6+i,6000000000+i*2000000000,identity());t=tracking(r,identity());out=s.update(r,&t);CHECK(out.raw_pose_valid);}
  CHECK(out.alignment_valid&&out.state==ATC_SESSION_TRACKING);near(out.world_from_scan,identity());
 });
 test("old pinned tracking epoch cannot clear established current alignment",[]{
  Session s;CHECK(atc_session_reset(s.h,7,4)==ATC_OK);ready(s,identity(),identity());
  auto r=raw(4,130000000,identity());auto t=tracking(r,rotateZ(0,10));t.tracking_epoch=3;const auto rejected=s.update(r,&t);
  CHECK(rejected.raw_pose_valid&&!rejected.alignment_valid&&rejected.rejection_reason==ATC_REJECTION_IDENTITY&&rejected.state==ATC_SESSION_TRACKING);
  r=raw(5,140000000,identity(),false);t=tracking(r,identity());const auto out=s.update(r,&t,ATC_NO_MATCH);
  CHECK(out.propagated_pose_valid&&out.alignment_valid&&out.state==ATC_SESSION_TRACKING);near(out.world_from_scan,identity());
 });
 test("three samples initialize asymmetric composition",[&]{Session s;ready(s,cs,wc);auto r=raw(4,130000000,cs);auto t=tracking(r,wc);auto out=s.update(r,&t);CHECK(out.state==ATC_SESSION_TRACKING&&out.mode==ATC_MODE_ALIGNED&&out.raw_pose_valid&&out.alignment_valid&&!out.propagated_pose_valid&&out.tracking_epoch==4&&out.alignment_age_ns==0);near(out.world_from_scan,ws);});
 test("no-match tracking propagation is not visual success",[&]{Session s;ready(s,cs,wc);auto r=raw(4,130000000,identity(),false);auto moved=multiply(rotateZ(.2,1,2,3),wc);auto t=tracking(r,moved);auto out=s.update(r,&t,ATC_NO_MATCH);CHECK(!out.raw_pose_valid&&out.alignment_valid&&out.propagated_pose_valid&&out.mode==ATC_MODE_PROPAGATED&&out.alignment_age_ns==10000000);near(out.world_from_scan,ws);near(out.camera_from_scan,multiply(inverse(moved),ws));});
 test("no-match without alignment cannot propagate",[&]{Session s;auto r=raw(1,100,identity(),false);auto t=tracking(r,wc);auto out=s.update(r,&t,ATC_NO_MATCH);CHECK(!out.raw_pose_valid&&!out.alignment_valid&&!out.propagated_pose_valid&&out.mode==ATC_MODE_NONE);});
 test("alignment expires without refreshing visual capture on propagation",[&]{Session s;ready(s,cs,wc);auto r=raw(4,130000000,identity(),false);auto t=tracking(r,wc);CHECK(s.update(r,&t,ATC_NO_MATCH).propagated_pose_valid);r=raw(5,1120000001,identity(),false);t=tracking(r,wc);auto out=s.update(r,&t,ATC_NO_MATCH);CHECK(out.state==ATC_SESSION_LOST&&!out.alignment_valid&&!out.propagated_pose_valid&&out.rejection_reason==ATC_REJECTION_ALIGNMENT_AGE);for(uint64_t i=0;i<2;++i){r=raw(6+i,1130000000+i*10000000,cs);t=tracking(r,wc);out=s.update(r,&t);CHECK(out.alignment_valid==(i==1));}CHECK(out.state==ATC_SESSION_TRACKING);});
 test("age limit inclusive and uint64 subtraction safe",[&]{Session s;ready(s,cs,wc,1,std::numeric_limits<uint64_t>::max()-2000000000);auto r=raw(4,std::numeric_limits<uint64_t>::max()-980000000,identity(),false);auto t=tracking(r,wc);const auto out=s.update(r,&t,ATC_NO_MATCH);CHECK(out.alignment_age_ns==1000000000&&out.alignment_valid);});
 const std::vector<std::pair<std::string,std::function<void(ATCTrackingSampleV2&)>>> invalidTracking={
  {"frame identity",[](auto& t){++t.frame_id;}},{"capture identity",[](auto& t){++t.capture_timestamp_ns;}},{"generation identity",[](auto& t){++t.map_generation;}},{"clock identity",[](auto& t){++t.capture_clock_epoch;}},{"camera identity",[](auto& t){++t.camera_id;}}
 };
 for(const auto& item:invalidTracking)test(item.first,[&]{Session s;auto r=raw(1,100,cs);auto t=tracking(r,wc);item.second(t);auto out=s.update(r,&t);CHECK(out.raw_pose_valid&&!out.alignment_valid&&out.mode==ATC_MODE_RAW&&out.rejection_reason==ATC_REJECTION_IDENTITY);near(out.camera_from_scan,cs);});
 test("unknown clock mapping retains Raw",[&]{Session s;auto r=raw(1,100,cs);auto t=tracking(r,wc);t.clock_mapping_valid=0;auto out=s.update(r,&t);CHECK(out.raw_pose_valid&&!out.alignment_valid&&out.rejection_reason==ATC_REJECTION_CLOCK_MAPPING);});
 for(const auto& item:std::vector<std::pair<std::string,std::function<void(ATCTrackingSampleV2&)>>>{{"invalid pose flag",[](auto& t){t.pose_valid=0;}},{"invalid extrinsics",[](auto& t){t.extrinsics_valid=0;}},{"limited tracking",[](auto& t){t.tracking_quality=ATC_TRACKING_QUALITY_LIMITED;}},{"unavailable tracking",[](auto& t){t.tracking_quality=ATC_TRACKING_QUALITY_UNAVAILABLE;}},{"reflected tracking",[](auto& t){t.world_from_camera[0]*=-1;t.world_from_camera[4]*=-1;t.world_from_camera[8]*=-1;}},{"nonfinite tracking",[](auto& t){t.world_from_camera[3]=NAN;}},{"sheared tracking",[](auto& t){t.world_from_camera[0]+=.2f;}}})test(item.first,[&]{Session s;auto r=raw(1,100,cs);auto t=tracking(r,wc);item.second(t);auto out=s.update(r,&t);CHECK(out.raw_pose_valid&&!out.alignment_valid&&out.rejection_reason==ATC_REJECTION_TRACKING_INVALID);});
 test("invalid uint32 tracking flag rejected without erasing Raw",[&]{Session s;auto r=raw(1,100,cs);auto t=tracking(r,wc);t.extrinsics_valid=2;const auto out=s.update(r,&t,ATC_INVALID_ARGUMENT);CHECK(out.raw_pose_valid&&!out.alignment_valid);});
 test("short tracking prefix retains readable Raw",[&]{Session s;auto r=raw(1,100,cs);auto t=tracking(r,wc);t.struct_size=8;const auto out=s.update(r,&t,ATC_ABI_MISMATCH);CHECK(out.raw_pose_valid&&!out.alignment_valid);});
 test("numeric pose skew both directions and inclusive bound",[&]{for(int direction:{-1,1}){Session s;auto r=raw(1,100000000,cs);auto t=tracking(r,wc);t.pose_timestamp_ns=r.capture_timestamp_ns+direction*5000000;auto out=s.update(r,&t);CHECK(out.raw_pose_valid&&out.rejection_reason==ATC_REJECTION_NONE);r.frame_id++;r.capture_timestamp_ns+=10000000;t=tracking(r,wc);t.pose_timestamp_ns=r.capture_timestamp_ns+direction*5000001;out=s.update(r,&t);CHECK(out.raw_pose_valid&&!out.alignment_valid&&out.rejection_reason==ATC_REJECTION_POSE_SKEW);}});
 test("outlier translation separately rejects world alignment",[&]{Session s;ready(s,cs,wc);auto r=raw(4,130000000,cs);auto t=tracking(r,wc);t.world_from_camera[3]+=.251f;const auto out=s.update(r,&t);CHECK(out.raw_pose_valid&&!out.alignment_valid&&out.mode==ATC_MODE_RAW&&out.rejection_reason==ATC_REJECTION_OUTLIER);});
 test("outlier SO3 angle separately rejects alignment",[&]{Session s;ready(s,cs,wc);auto r=raw(4,130000000,cs);auto changed=multiply(rotateZ(6*pi/180),wc);changed[3]=wc[3];changed[7]=wc[7];changed[11]=wc[11];auto t=tracking(r,changed);const auto out=s.update(r,&t);CHECK(out.raw_pose_valid&&!out.alignment_valid&&out.rejection_reason==ATC_REJECTION_OUTLIER);});
 test("initialization restarts after inconsistent candidate",[&]{Session s;auto r=raw(1,100000000,cs);auto t=tracking(r,wc);CHECK(!s.update(r,&t).alignment_valid);r=raw(2,110000000,cs);t=tracking(r,wc);t.world_from_camera[3]+=10;CHECK(s.update(r,&t).rejection_reason==ATC_REJECTION_OUTLIER);for(uint64_t i=0;i<3;++i){r=raw(3+i,120000000+i*10000000,cs);t=tracking(r,wc);CHECK(s.update(r,&t).alignment_valid==(i==2));}});
 test("world origin transform does not alter acceptance",[&]{Session a,b;const Matrix origin=rotateZ(.6,100,-37,53);for(uint64_t i=0;i<7;++i){auto r=raw(i+1,100000000+i*10000000,cs);Matrix moved=wc;if(i==3)moved[3]+=.1f;if(i==5)moved[3]+=2;auto ta=tracking(r,moved),tb=tracking(r,multiply(origin,moved));const auto oa=a.update(r,&ta),ob=b.update(r,&tb);CHECK(oa.rejection_reason==ob.rejection_reason&&oa.alignment_valid==ob.alignment_valid&&oa.state==ob.state);if(oa.alignment_valid)near(ob.world_from_scan,multiply(origin,matrix(oa.world_from_scan)),.0003f);}});
 test("SE3 time smoothing has expected translation and rotation",[]{auto c=config();c.window_size=c.initialization_samples=c.recovery_samples=1;c.max_translation_residual_m=10;c.max_rotation_residual_rad=pi;c.max_alignment_age_ns=3000000000;c.smoothing_tau_seconds=1;Session s(c);auto r=raw(1,0,identity());auto t=tracking(r,identity());CHECK(s.update(r,&t).alignment_valid);r=raw(2,1000000000,identity());t=tracking(r,rotateZ(pi/2,1,0,0));const auto out=s.update(r,&t);const double alpha=1-std::exp(-1.0);near(out.world_from_scan,rotateZ(alpha*pi/2,alpha,0,0));});
 test("time smoothing is independent of intermediate sample rate",[]{auto c=config();c.window_size=c.initialization_samples=c.recovery_samples=1;c.max_translation_residual_m=10;c.max_rotation_residual_rad=pi;c.max_alignment_age_ns=3000000000;c.smoothing_tau_seconds=1;Session a(c),b(c);for(auto* s:{&a,&b}){auto r=raw(1,0,identity());auto t=tracking(r,identity());s->update(r,&t);}auto r=raw(2,1000000000,identity());auto t=tracking(r,rotateZ(pi/2,1));const auto full=a.update(r,&t);r=raw(2,500000000,identity());t=tracking(r,rotateZ(pi/2,1));b.update(r,&t);r=raw(3,1000000000,identity());t=tracking(r,rotateZ(pi/2,1));near(b.update(r,&t).world_from_scan,matrix(full.world_from_scan));});
 test("SO3 interpolation shortest arc across angle wrap",[]{auto c=config();c.window_size=c.initialization_samples=c.recovery_samples=1;c.max_rotation_residual_rad=pi;c.smoothing_tau_seconds=1;Session s(c);auto r=raw(1,0,identity());auto t=tracking(r,rotateZ(179*pi/180));s.update(r,&t);r=raw(2,693147181,identity());t=tracking(r,rotateZ(-179*pi/180));const auto out=s.update(r,&t);near(out.world_from_scan,rotateZ(pi));});
 test("disabled smoothing applies current candidate",[]{auto c=config();c.window_size=c.initialization_samples=c.recovery_samples=1;c.max_translation_residual_m=2;c.max_rotation_residual_rad=pi;Session s(c);auto r=raw(1,0,identity());auto t=tracking(r,identity());s.update(r,&t);r=raw(2,100,identity());t=tracking(r,rotateZ(.7,1));near(s.update(r,&t).world_from_scan,rotateZ(.7,1));});
 test("duplicate frame and reversed time are stale with no validity",[&]{Session s;auto r=raw(1,100,cs);auto t=tracking(r,wc);s.update(r,&t);auto out=s.update(r,&t,ATC_STALE_FRAME);CHECK(!out.raw_pose_valid&&!out.alignment_valid&&out.rejection_reason==ATC_REJECTION_STALE_FRAME);r.frame_id=2;r.capture_timestamp_ns=99;t=tracking(r,wc);CHECK(!s.update(r,&t,ATC_STALE_FRAME).raw_pose_valid);r.capture_timestamp_ns=101;t=tracking(r,wc);CHECK(s.update(r,&t).raw_pose_valid);});
 for(const auto& item:std::vector<std::pair<std::string,std::function<void(ATCResultV2&)>>>{{"raw generation requires reset",[](auto& r){++r.map_generation;}},{"raw map instance requires reset",[](auto& r){++r.map_instance_id;}},{"raw capture clock requires reset",[](auto& r){++r.capture_clock_epoch;}},{"raw camera requires reset",[](auto& r){++r.camera_id;}}})test(item.first,[&]{Session s;ready(s,cs,wc);auto r=raw(4,130000000,cs);item.second(r);auto t=tracking(r,wc);auto out=s.update(r,&t,ATC_STALE_FRAME);CHECK(!out.raw_pose_valid&&!out.alignment_valid&&!out.propagated_pose_valid);});
 test("tracking origin change clears previous alignment",[&]{Session s;ready(s,cs,wc);auto r=raw(4,130000000,cs);auto t=tracking(r,multiply(rotateZ(.5,20,30,40),wc));++t.tracking_epoch;auto out=s.update(r,&t);CHECK(out.raw_pose_valid&&!out.alignment_valid&&out.state==ATC_SESSION_INITIALIZING);for(uint64_t i=0;i<2;++i){r=raw(5+i,140000000+i*10000000,cs);t=tracking(r,multiply(rotateZ(.5,20,30,40),wc));t.tracking_epoch=5;out=s.update(r,&t);}CHECK(out.alignment_valid&&out.tracking_epoch==5);});
 test("reset pins generation and epoch and rejects late old result",[&]{Session s;ready(s,cs,wc);CHECK(atc_session_reset(s.h,8,9)==ATC_OK);auto old=raw(4,130000000,cs);auto t=tracking(old,wc);CHECK(!s.update(old,&t,ATC_STALE_FRAME).raw_pose_valid);auto r=raw(0,0,cs);r.map_generation=8;r.map_instance_id=32;r.capture_clock_epoch=12;r.camera_id=3;t=tracking(r,wc);auto out=s.update(r,&t);CHECK(out.raw_pose_valid&&!out.alignment_valid&&out.rejection_reason==ATC_REJECTION_IDENTITY);for(uint64_t i=0;i<3;++i){r=raw(i+1,100+i*100,cs);r.map_generation=8;r.map_instance_id=32;r.capture_clock_epoch=12;r.camera_id=3;t=tracking(r,wc);t.tracking_epoch=9;out=s.update(r,&t);}CHECK(out.alignment_valid&&out.tracking_epoch==9);});
 test("independent sessions do not share alignment",[&]{Session a,b;ready(a,cs,wc);auto r=raw(4,130000000,cs);auto t=tracking(r,wc);CHECK(a.update(r,&t).alignment_valid);CHECK(!b.update(r,&t).alignment_valid);CHECK(atc_session_reset(a.h,7,4)==ATC_OK);r=raw(5,140000000,cs);t=tracking(r,wc);CHECK(!a.update(r,&t).alignment_valid&&!b.update(r,&t).alignment_valid);});
 for(const auto& item:std::vector<std::pair<std::string,std::function<void(ATCResultV2&)>>>{{"nonfinite Raw",[](auto& r){r.camera_from_scan[3]=NAN;}},{"nonrigid Raw",[](auto& r){r.camera_from_scan[0]=2;}},{"bad Raw flag",[](auto& r){r.raw_pose_valid=2;}},{"bad metric flag",[](auto& r){r.reprojection_error_valid=2;}},{"bad confidence",[](auto& r){r.confidence=1.1f;}},{"bad metric",[](auto& r){r.reprojection_error_valid=1;r.reprojection_rmse_px=NAN;}},{"inconsistent Raw success",[](auto& r){r.status=ATC_NO_MATCH;}}})test(item.first,[&]{Session s;auto r=raw(1,100,cs);item.second(r);auto t=tracking(r,wc);auto out=s.update(r,&t,ATC_INVALID_ARGUMENT);CHECK(!out.raw_pose_valid&&!out.alignment_valid&&!out.propagated_pose_valid&&out.rejection_reason==ATC_REJECTION_INVALID_RAW);});
 test("Raw error cannot propagate stored alignment",[&]{Session s;ready(s,cs,wc);auto r=raw(4,130000000,identity(),false);r.status=ATC_INTERNAL_ERROR;auto t=tracking(r,wc);auto out=s.update(r,&t,ATC_INTERNAL_ERROR);CHECK(!out.raw_pose_valid&&!out.alignment_valid&&!out.propagated_pose_valid&&out.rejection_reason==ATC_REJECTION_INVALID_RAW);});
 test("ABI output canary and unreadable tracking tail",[&]{Session s;auto r=raw(1,100,cs);struct Guard{uint32_t size=8,version=2;unsigned char canary[64];}guard;std::fill(std::begin(guard.canary),std::end(guard.canary),0xA5);CHECK(atc_session_update(s.h,&r,nullptr,reinterpret_cast<ATCSessionResultV2*>(&guard))==ATC_ABI_MISMATCH);for(auto c:guard.canary)CHECK(c==0xA5);ATCSessionResultV2 out{};out.struct_size=sizeof(out);out.api_version=2;guard.size=8;CHECK(atc_session_update(s.h,&r,reinterpret_cast<ATCTrackingSampleV2*>(&guard),&out)==ATC_ABI_MISMATCH&&out.raw_pose_valid);});
 test("larger output tail untouched",[&]{Session s;auto r=raw(1,100,cs);struct Extended{ATCSessionResultV2 out{};unsigned char tail[16];}e;e.out.struct_size=sizeof(e);e.out.api_version=2;std::fill(std::begin(e.tail),std::end(e.tail),0x5A);CHECK(atc_session_update(s.h,&r,nullptr,&e.out)==ATC_OK);for(auto c:e.tail)CHECK(c==0x5A);});
 test("null arguments and repeat destroy are safe",[&]{Session s;auto r=raw(1,100,cs);ATCSessionResultV2 out{};out.struct_size=sizeof(out);out.api_version=2;CHECK(atc_session_update(nullptr,&r,nullptr,&out)==ATC_INVALID_ARGUMENT);CHECK(atc_session_update(s.h,nullptr,nullptr,&out)==ATC_INVALID_ARGUMENT);CHECK(atc_session_update(s.h,&r,nullptr,nullptr)==ATC_INVALID_ARGUMENT);CHECK(atc_session_reset(nullptr,0,0)==ATC_INVALID_ARGUMENT);atc_session_destroy(nullptr);atc_session_destroy(&s.h);CHECK(s.h==nullptr);atc_session_destroy(&s.h);});
 for(const auto& item:std::vector<std::pair<std::string,std::function<void(ATCSessionConfigV2&)>>>{{"zero window",[](auto& c){c.window_size=0;}},{"zero init samples",[](auto& c){c.initialization_samples=0;}},{"init beyond window",[](auto& c){c.initialization_samples=6;}},{"zero recovery",[](auto& c){c.recovery_samples=0;}},{"recovery beyond window",[](auto& c){c.recovery_samples=6;}},{"zero translation threshold",[](auto& c){c.max_translation_residual_m=0;}},{"nonfinite rotation threshold",[](auto& c){c.max_rotation_residual_rad=NAN;}},{"zero skew",[](auto& c){c.max_pose_skew_ns=0;}},{"zero alignment age",[](auto& c){c.max_alignment_age_ns=0;}},{"zero host result age",[](auto& c){c.max_result_age_ns=0;}},{"negative tau",[](auto& c){c.smoothing_tau_seconds=-1;}},{"nonfinite tau",[](auto& c){c.smoothing_tau_seconds=INFINITY;}}})test(item.first,[&]{auto c=config();item.second(c);ATCSessionHandle h=reinterpret_cast<void*>(1);CHECK(atc_session_create(&c,&h)==ATC_INVALID_ARGUMENT&&h==nullptr);});
 test("config ABI validates prefix before fields",[]{auto c=config();c.struct_size=8;ATCSessionHandle h=nullptr;CHECK(atc_session_create(&c,&h)==ATC_ABI_MISMATCH&&!h);c=config();c.api_version=1;CHECK(atc_session_create(&c,&h)==ATC_ABI_MISMATCH);CHECK(atc_session_create(nullptr,&h)==ATC_INVALID_ARGUMENT);CHECK(atc_session_create(&c,nullptr)==ATC_INVALID_ARGUMENT);});
 std::cout<<"Session: "<<cases<<" numeric/state/ABI cases passed using shared nonidentity fixture; "<<failures<<" failed\n";if(failures)return 1;
 }catch(const std::exception& e){std::cerr<<e.what()<<'\n';return 1;}}
